# Generated by Django 4.2.2 on 2023-07-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
