# Generated by Django 4.2.2 on 2023-07-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_delete_rating'),
        ('orders', '0002_remove_orderitem_order_remove_orderitem_product_and_more'),
        ('products', '0002_alter_product_category_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
