# Generated by Django 4.2.2 on 2023-07-01 10:57

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='products/', validators=[products.models.validate_image_file]),
        ),
    ]
